# Generated by Django 4.2.2 on 2023-09-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "phone_number",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(max_length=10)),
                ("is_valid", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "User",
            },
        ),
    ]
